// packages/lumen-react/src/LumenCanvas.tsx
import { useEffect, useRef } from "react";

import type { CSSProperties } from "react";
import { LumenAudioEngine, createLumenPreviewRuntime } from "lumen-preview";
import type {
  AudioEngineTimeline,
  AudioSourceRegistration,
  LumenPreviewBindings,
  LumenPreviewController,
} from "lumen-preview";

import type { LumenPreviewContext } from "./preview.ts";

export interface LumenCanvasProps {
  preview: LumenPreviewContext;
  bindings: LumenPreviewBindings;
  audioSources?: AudioSourceRegistration[];
  audioTimeline?: AudioEngineTimeline | null;
  compositionJson?: string | null;
  fps?: number;
  className?: string;
  style?: CSSProperties;
}

export function LumenCanvas({
  preview,
  bindings,
  audioSources = [],
  audioTimeline = null,
  compositionJson = null,
  fps = 30,
  className,
  style,
}: LumenCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const audioEngineRef = useRef<LumenAudioEngine | null>(null);
  const controllerRef = useRef<LumenPreviewController | null>(null);
  const queuedRenderRef = useRef<(() => Promise<void>) | null>(null);
  const renderInFlightRef = useRef(false);
  const animationFrameRef = useRef(0);
  const compositionLoadedRef = useRef(false);

  function describeError(error: unknown): string {
    if (error instanceof Error) {
      return error.stack ?? `${error.name}: ${error.message}`;
    }

    return String(error);
  }

  function reportError(scope: string, error: unknown): void {
    console.error(`[LumenCanvas] ${scope}`, error);
    preview.update({ error: describeError(error) });
  }

  function hasLoadedComposition(): boolean {
    return compositionLoadedRef.current;
  }

  function queueRender(operation: () => Promise<void>): void {
    queuedRenderRef.current = operation;
    if (renderInFlightRef.current) {
      return;
    }

    void drainRenderQueue();
  }

  async function drainRenderQueue(): Promise<void> {
    renderInFlightRef.current = true;

    try {
      while (queuedRenderRef.current) {
        const next = queuedRenderRef.current;
        queuedRenderRef.current = null;
        await next();
      }
    } finally {
      renderInFlightRef.current = false;
      if (queuedRenderRef.current) {
        void drainRenderQueue();
      }
    }
  }

  async function renderOnce(controller: LumenPreviewController): Promise<void> {
    const canvas = canvasRef.current;
    if (!canvas) {
      return;
    }
    if (!hasLoadedComposition()) {
      return;
    }

    try {
      const startedAt = performance.now();
      await controller.renderNowAsync(canvas);
      preview.update({
        frame: controller.currentFrame(),
        renderMs: performance.now() - startedAt,
        isPlaying: controller.isPlaying(),
        error: null,
      });
    } catch (error) {
      reportError("renderOnce", error);
    }
  }

  function handleLoadComposition(
    controller: LumenPreviewController,
    json: string,
    nextFps: number,
  ): void {
    try {
      controller.loadComposition(json, nextFps);
      compositionLoadedRef.current = true;
      preview.update({
        totalFrames: controller.durationFrames(),
        width: controller.width(),
        height: controller.height(),
        isLoaded: true,
        error: null,
      });
    } catch (error) {
      compositionLoadedRef.current = false;
      preview.update({ isLoaded: false });
      reportError("loadComposition", error);
    }
  }

  function startLoop(controller: LumenPreviewController): void {
    cancelAnimationFrame(animationFrameRef.current);
    animationFrameRef.current = 0;

    const loop = (now: number): void => {
      animationFrameRef.current = 0;
      const canvas = canvasRef.current;

      if (canvas) {
        const audioEngine = audioEngineRef.current;
        const snapshot = preview.getSnapshot();
        const shouldRenderTick =
          hasLoadedComposition() && (controller.isPlaying() || snapshot.isPlaying);

        if (shouldRenderTick) {
          queueRender(async () => {
            if (!hasLoadedComposition()) {
              return;
            }

            if (audioEngine && audioTimeline && preview.getSnapshot().isPlaying) {
              const targetFrame = controller.targetFrameForTimeMs(audioEngine.currentTimeMs());
              try {
                controller.setFrame(targetFrame);
                const startedAt = performance.now();
                await controller.renderNowAsync(canvas);
                preview.update({
                  frame: targetFrame,
                  renderMs: performance.now() - startedAt,
                  isPlaying: controller.isPlaying(),
                  error: null,
                });
              } catch (error) {
                reportError("audio-clock animation tick", error);
              }
              return;
            }

            try {
              const startedAt = performance.now();
              const changed = await controller.tickAsync(now, canvas);
              if (changed) {
                const currentFrame = controller.currentFrame();
                preview.update({
                  frame: currentFrame,
                  renderMs: performance.now() - startedAt,
                  isPlaying: controller.isPlaying(),
                  error: null,
                });
              }
            } catch (error) {
              reportError("animation tick", error);
            }
          });
        }
      }

      animationFrameRef.current = requestAnimationFrame(loop);
    };

    animationFrameRef.current = requestAnimationFrame(loop);
  }

  useEffect(() => {
    let cancelled = false;
    const { LumenPreviewController: PreviewController } = createLumenPreviewRuntime(bindings);

    Promise.resolve()
      .then(() => {
        if (cancelled) {
          return;
        }

        const controller = new PreviewController();
        const audioEngine = new LumenAudioEngine();
        compositionLoadedRef.current = false;
        audioEngineRef.current = audioEngine;
        controllerRef.current = controller;
        preview._attach(
          controller,
          (frame) => {
            queueRender(async () => {
              try {
                controller.setFrame(frame);
                await renderOnce(controller);
              } catch (error) {
                reportError("seek render", error);
              }
            });
          },
          {
            pause: () => audioEngine.pause(),
            play: () => {
              const frame = controller.currentFrame();
              audioEngine.play((frame / Math.max(fps, 1)) * 1000);
            },
            seek: (frame) => audioEngine.seekMs((frame / Math.max(fps, 1)) * 1000),
          },
        );
        if (compositionJson) {
          handleLoadComposition(controller, compositionJson, fps);
          queueRender(() => renderOnce(controller));
        }
        startLoop(controller);
      })
      .catch((error: unknown) => {
        if (!cancelled) {
          reportError("initialize lumen-preview", error);
        }
      });

    return () => {
      cancelled = true;
      cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = 0;
      audioEngineRef.current?.dispose();
      audioEngineRef.current = null;
      controllerRef.current?.clear();
      controllerRef.current = null;
      compositionLoadedRef.current = false;
      preview._detach();
    };
  }, [preview, bindings, compositionJson, fps]);

  useEffect(() => {
    const audioEngine = audioEngineRef.current;
    if (!audioEngine) {
      return;
    }

    audioEngine.setAudioTimeline(audioTimeline);
    void audioEngine.syncAudioSources(audioSources).catch((error: unknown) => {
      reportError("sync audio sources", error);
    });
  }, [audioSources, audioTimeline]);

  useEffect(() => {
    const controller = controllerRef.current;
    if (!controller || !compositionJson) {
      compositionLoadedRef.current = false;
      preview.update({ isLoaded: false });
      return;
    }

    handleLoadComposition(controller, compositionJson, fps);
    queueRender(() => renderOnce(controller));
  }, [compositionJson, fps, preview]);

  const snapshot = preview.getSnapshot();

  return (
    <canvas
      ref={canvasRef}
      width={snapshot.width || 1}
      height={snapshot.height || 1}
      className={className}
      style={style}
    />
  );
}

// packages/lumen-svelte/src/LumenCanvas.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { createLumenPreviewRuntime } from "lumen-preview";
    import type { LumenPreviewBindings, LumenPreviewController } from "lumen-preview";
    import type { LumenPreviewContext } from "./preview.svelte.js";

    type Props = {
        preview: LumenPreviewContext;
        bindings: LumenPreviewBindings;
        compositionJson?: string | null;
        fps?: number;
        class?: string;
        style?: string;
    };

    let {
        preview,
        bindings,
        compositionJson = null,
        fps = 30,
        class: className,
        style: styleName,
    }: Props = $props();

    let canvas = $state<HTMLCanvasElement | null>(null);
    let ctrl = $state<LumenPreviewController | null>(null);
    let rafId = 0;
    let compositionLoaded = false;

    function getCtx2d(): CanvasRenderingContext2D | null {
        return canvas?.getContext("2d") ?? null;
    }

    let renderInFlight = false;
    let queuedRender: (() => Promise<void>) | null = null;

    function describeError(error: unknown): string {
        if (error instanceof Error) {
            return error.stack ?? `${error.name}: ${error.message}`;
        }
        return String(error);
    }

    function reportError(scope: string, error: unknown): void {
        console.error(`[LumenCanvas] ${scope}`, error);
        preview.update({ error: describeError(error) });
    }

    function queueRender(operation: () => Promise<void>): void {
        queuedRender = operation;
        if (renderInFlight) {
            return;
        }
        void drainRenderQueue();
    }

    async function drainRenderQueue(): Promise<void> {
        renderInFlight = true;
        try {
            while (queuedRender) {
                const next = queuedRender;
                queuedRender = null;
                await next();
            }
        } finally {
            renderInFlight = false;
            if (queuedRender) {
                void drainRenderQueue();
            }
        }
    }

    async function renderOnce(controller: LumenPreviewController): Promise<void> {
        const ctx = getCtx2d();
        if (!ctx) return;
        if (!compositionLoaded) return;
        try {
            const t0 = performance.now();
            await controller.renderNowAsync(ctx);
            preview.update({
                renderMs: performance.now() - t0,
                frame: controller.currentFrame(),
                isPlaying: controller.isPlaying(),
                error: null,
            });
        } catch (e: unknown) {
            reportError("renderOnce", e);
        }
    }

    function handleLoadComposition(
        controller: LumenPreviewController,
        json: string,
        f: number,
    ): void {
        try {
            controller.loadComposition(json, f);
            compositionLoaded = true;
            preview.update({
                totalFrames: controller.durationFrames(),
                width: controller.width(),
                height: controller.height(),
                error: null,
            });
        } catch (e: unknown) {
            compositionLoaded = false;
            reportError("loadComposition", e);
        }
    }

    function startLoop(controller: LumenPreviewController): void {
        cancelAnimationFrame(rafId);
        rafId = 0;

        function loop(now: number): void {
            rafId = 0;
            const ctx = getCtx2d();

            if (ctx && compositionLoaded && controller.isPlaying()) {
                queueRender(async () => {
                    if (!compositionLoaded) {
                        return;
                    }

                    try {
                        const t0 = performance.now();
                        const changed = await controller.tickAsync(now, ctx);
                        if (changed) {
                            preview.update({
                                renderMs: performance.now() - t0,
                                frame: controller.currentFrame(),
                                isPlaying: controller.isPlaying(),
                            });
                        }
                        preview.update({ error: null });
                    } catch (e: unknown) {
                        reportError("animation tick", e);
                        // Don't return — keep the loop alive so transient errors
                        // (e.g. media not yet loaded) recover automatically.
                    }
                });
            }

            rafId = requestAnimationFrame(loop);
        }

        rafId = requestAnimationFrame(loop);
    }

    onMount(() => {
        let cancelled = false;

        Promise.resolve()
            .then(() => {
                if (cancelled) return;
                const { LumenPreviewController } = createLumenPreviewRuntime(bindings);
                const controller = new LumenPreviewController();
                compositionLoaded = false;
                preview._attach(controller, (frame) => {
                    queueRender(async () => {
                        try {
                            controller.setFrame(frame);
                            await renderOnce(controller);
                        } catch (e: unknown) {
                            reportError("seek render", e);
                        }
                    });
                });
                ctrl = controller;
                startLoop(controller);
            })
            .catch((e: unknown) => {
                if (!cancelled) {
                    reportError("initialize lumen-preview", e);
                }
            });

        return () => {
            cancelled = true;
            cancelAnimationFrame(rafId);
            rafId = 0;
            compositionLoaded = false;
            ctrl?.clear();
            preview._detach();
            ctrl = null;
        };
    });

    // Load/reload composition when compositionJson, fps, or ctrl changes
    $effect(() => {
        const json = compositionJson;
        const f = fps;
        const controller = ctrl;
        if (!controller || !json) {
            compositionLoaded = false;
            return;
        }
        handleLoadComposition(controller, json, f);
        queueRender(() => renderOnce(controller));
    });
</script>

<canvas
    bind:this={canvas}
    width={preview.width || 1}
    height={preview.height || 1}
    style={styleName}
    style:visibility={preview.width > 0 ? null : "hidden"}
    class={className}
></canvas>
